#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://3.35.255.89:3306/longstonedb?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=kddnswlr
#spring.datasource.password=KDkd4813*

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.35.255.89:3306/longstonedb?serverTimezone=UTC&characterEncoding=UTF-8
    username: kddnswlr
    password: KDkd4813*
#//jsp
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

logging:
  level:
    com:
      demo: debug

# HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ?
# Secret ?? ?? ???? Base64 ? ???? ? ?? (?? ???? ???? ??? ??? ??)
# echo -n 'hello-my-real-name-is-wonjun-this-key-is-very-important-so-be-careful-thank-you' | openssl base64
# 1800000 30?
# 604800000 1??

jwt:
  header: Authorization
  secret: aGVsbG8tbXktcmVhbC1uYW1lLWlzLXdvbmp1bi10aGlzLWtleS1pcy12ZXJ5LWltcG9ydGFudC1zby1iZS1jYXJlZnVsLXRoYW5rLXlvdQ==
  access-token-expire-time: 1800000
  refresh-token-expire-time: 604800000

---

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 32

  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

---

spring:
  config:
    activate:
      on-profile: test

---

spring:
  config:
    activate:
      on-profile: prod